### ISSUE TITLE
I don't know how to run this script and input parameters.

### ISSUE THREAD

**Issue by BerlinWu** [alexschimpf/Snkrs-Bot#3]
When I run the script and input some parameters to it,like USERNAME PASSWORD URL and SHOT_SIZE,it only will output error,like this(cmd):

C:\Users\Berli\AppData\Local\Programs\Python\Python37\Scripts>main.py --username ********* --password ********* --url https://www.nike.com/cn/launch/t/m2k-tekno-pure-platinum-sail-black/ --shoe-size 42 --driver-type chrome
usage: main.py [-h] --username USERNAME --password PASSWORD --url URL
               --shoe-size SHOE_SIZE [--login-time LOGIN_TIME]
               [--release-time RELEASE_TIME]
               [--screenshot-path SCREENSHOT_PATH]
               [--page-load-timeout PAGE_LOAD_TIMEOUT]
               [--driver-type {firefox,chrome}] [--headless]
               [--select-payment] [--purchase] [--num-retries NUM_RETRIES]
main.py: error: the following arguments are required: --username, --password, --url, --shoe-size

I don't know how to input,please give me some advice.Thank you so much!!!

**Comment by alexschimpf** [comment]
1. I have not included a Selenium driver for Windows, so keep that in mind. You can add one yourself if you'd like.
2. The script will not work for the China site because the XPaths are meant for the English site. You'll have to change them yourself.
3. You'll probably want to wrap your arguments in quotes to be safe.
``python main.py --username 'test' --password 'test' --url 'https://www.nike.com/cn/launch/t/m2k-tekno-pure-platinum-sail-black/' --shoe-size 42 --driver-type 'chrome'``
